# -*- coding: utf-8 -*-
"""TrabalhoYvoAtualizado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8br7mRhajl0YHwGUC89PxknxXJsWhi3
"""

import numpy as np

def simplex_tableau(c, A, b):
    """Executa o método Simplex Tableau passo a passo."""
    m, n = A.shape
    tableau = np.zeros((m + 1, n + m + 1))
    tableau[:m, :n] = A
    tableau[:m, n:n+m] = np.eye(m)
    tableau[:m, -1] = b
    tableau[-1, :n] = -c

    base_vars = list(range(n, n + m))

    while True:
        if np.all(tableau[-1, :-1] >= 0):
            break

        col = np.argmin(tableau[-1, :-1])
        if np.all(tableau[:-1, col] <= 0):
            raise ValueError("Problema ilimitado (não há solução ótima finita).")

        ratios = np.full(m, np.inf)
        for i in range(m):
            if tableau[i, col] > 0:
                ratios[i] = tableau[i, -1] / tableau[i, col]
        row = np.argmin(ratios)

        pivot = tableau[row, col]
        tableau[row, :] /= pivot

        for i in range(m + 1):
            if i != row:
                tableau[i, :] -= tableau[i, col] * tableau[row, :]

        base_vars[row] = col

    solution = np.zeros(n + m)
    for i in range(m):
        solution[base_vars[i]] = tableau[i, -1]

    x = solution[:n]
    z = tableau[-1, -1]

    y = tableau[-1, n:n+m]  # preços sombra

    return x, z, y, tableau, base_vars


def entrada_dados():
    print("=== MÉTODO SIMPLEX TABLEAU ===")
    n = int(input("Número de variáveis da função objetivo: "))
    m = int(input("Número de restrições: "))

    print("\nCoeficientes da função objetivo (Z = c1*x1 + c2*x2 + ...):")
    c = np.array([float(input(f"c{i+1}: ")) for i in range(n)])

    print("\nInsira as restrições (do tipo <=):")
    A = np.zeros((m, n))
    b = np.zeros(m)
    for i in range(m):
        print(f"\nRestrição {i+1}:")
        for j in range(n):
            A[i, j] = float(input(f"Coeficiente de x{j+1}: "))
        b[i] = float(input("Termo independente (lado direito): "))

    return c, A, b


def analise_sensibilidade(y, b, z):
    print("\n=== ANÁLISE DE SENSIBILIDADE ===")
    for i, yi in enumerate(y):
        print(f"Preço-sombra da restrição {i+1}: {yi:.4f}")

    alterar = input("\nDeseja testar alteração em alguma restrição? (s/n): ").lower()
    if alterar == 's':
        i = int(input("Número da restrição que deseja alterar: ")) - 1
        delta = float(input("Variação no lado direito (Δb): "))

        novo_b = b.copy()
        novo_b[i] += delta

        novo_lucro = z + y[i] * delta
        if novo_b[i] >= 0:
            print(f"\nNova restrição é viável. Novo lucro ótimo ≈ {novo_lucro:.4f}")
        else:
            print("\nAlteração inviável (restrição negativa).")
    else:
        print("Nenhuma análise adicional realizada.")


def main():
    c, A, b = entrada_dados()

    try:
        x, z, y, tableau, base_vars = simplex_tableau(c, A, b)
        print("\n=== RESULTADO FINAL ===")
        for i, val in enumerate(x):
            print(f"x{i+1} = {val:.4f}")
        print(f"Lucro ótimo Z* = {z:.4f}")
        analise_sensibilidade(y, b, z)
    except ValueError as e:
        print(e)


if __name__ == "__main__":
    main()
1